---
  
- name:          Is siebweb path installed?
  stat:
    path:        "{{ siebweb_path }}/"
  register:      siebweb_path_installed
  
    

- name:           Building the siebweb_install response file
  template:
    src:          "{{siebweb_install_responsefile_j2}}"
    dest:         "{{siebweb_userhome}}/{{siebweb_install_responsefile_rsp}}" 
  when:           siebweb_path_installed.stat.exists == false or siebweb_install_force == true

- name:          Run silent installer for siebweb
  shell:         "cd {{ siebweb_source }} && yes | ./runInstaller -silent -silent -oneclick -responseFile {{siebweb_userhome}}/{{siebweb_install_responsefile_rsp}} -jreLoc {{app_dir}}/jre1.8.0_151 -invPtrLoc {{ siebweb_orainventory }}/{{ siebweb_orainst }}"
  register:      siebweb_silent_output
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_force == true
    
- debug:         var=siebweb_silent_output
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_force == true
  
  
  
- name:           chmod and chown to user and group siebweb
  file:
    path:         "{{siebweb_path}}"
    owner:        "{{app_user}}"
    group:        "{{app_group}}"
    mode:         0755
    recurse:      yes  
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_force == true    
  
  
  
- name:           Building the siebweb_install_patch response file
  template:
    src:          "{{siebweb_install_patch_responsefile_j2}}"
    dest:         "{{siebweb_userhome}}/{{siebweb_install_patch_responsefile_rsp}}" 
  when:           siebweb_path_installed.stat.exists == false or siebweb_install_patch_force == true  

- name:          Run silent installer for siebweb patch
  shell:         "cd {{ siebweb_source_patch }} && yes | ./runInstaller -silent -responseFile {{ siebweb_userhome }}/{{ siebweb_install_patch_responsefile_rsp }} -jreLoc {{app_dir}}/jre1.8.0_151 -invPtrLoc {{ siebweb_orainventory }}/{{ siebweb_orainst }}"
  register:      siebweb_silent_patch_output
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_patch_force == true
  
- debug:         var=siebweb_silent_patch_output 
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_patch_force == true
  
  

- name:           chmod and chown to user and group siebweb
  file:
    path:         "{{siebweb_path}}"
    owner:        "{{app_user}}"
    group:        "{{app_group}}"
    mode:         0755
    recurse:      yes 
  when:          siebweb_path_installed.stat.exists == false or siebweb_install_patch_force == true    
    
    
- debug:
    msg:          "!!!!!!!!!!!!!!!!!siebweb path EXIST or FORCE install or FORCE patch!!!!!!!!!!!!!!!!!"  
  when:           siebweb_path_installed.stat.exists == true 
  
      
       