---

- name:         Install pre-requisites
  yum:          name={{item}} state=present
  with_items:
                - "{{ihs_dependencies}}"  
  ignore_errors: true                 
  when:         (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS") 
  

- name:         Create Folders for IHS installation
  file:         path={{ item }} mode=0755 state=directory
  with_items: 
                - "{{ihs_directories}}" 
                